### ISSUE TITLE
Python >=3.12 Compatibility 

### ISSUE THREAD

**Issue by LiamOS** [DUNE/dunendggd#24]
[With python 3.12, SafeConfigParser has been removed; deprecated since 3.2.](https://docs.python.org/3/whatsnew/3.12.html)
New function as far as I can tell is configparser.ConfigParser, but it doesn't seem to 'just run' when I change only this. Maybe also need some `readfp` calls changed to `read_file`, unsure.
```
(env3.12)  liam@brick (~/dunendggd) % ./build_hall.sh miniproduction1_tms_nosand
Traceback (most recent call last):
  File "/home/liam/dunendggd/env3.12/lib/python3.12/site-packages/gegede/configuration.py", line 14, in parse
    try:                from ConfigParser import SafeConfigParser
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ConfigParser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liam/dunendggd/env3.12/bin/gegede-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liam/dunendggd/env3.12/lib/python3.12/site-packages/gegede/main.py", line 89, in main
    cfg = parse_config(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/dunendggd/env3.12/lib/python3.12/site-packages/gegede/main.py", line 27, in parse_config
    cfg = gegede.configuration.configure(filenames)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liam/dunendggd/env3.12/lib/python3.12/site-packages/gegede/configuration.py", line 106, in configure
    cfg = parse(filenames)
          ^^^^^^^^^^^^^^^^
  File "/home/liam/dunendggd/env3.12/lib/python3.12/site-packages/gegede/configuration.py", line 15, in parse
    except ImportError: from configparser import SafeConfigParser
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?```

**Comment by ast0815** [comment]
That looks like an upstream issue for https://github.com/brettviren/gegede. Maybe you could also push him to release the next version on PyPI, so we don't have to install a specific GitHub commit any more.
